import React from 'react';
import { Box, Typography, Button, Grid, Card, CardContent, Container } from '@mui/material';
import { Link } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import SecurityIcon from '@mui/icons-material/Security';
import EmojiObjectsIcon from '@mui/icons-material/EmojiObjects';
import TrendingUpIcon from '@mui/icons-material/TrendingUp';
import GroupsIcon from '@mui/icons-material/Groups';

const Home = () => {
  const { user } = useAuth();

  const features = [
    {
      icon: <SecurityIcon sx={{ fontSize: 60, color: 'primary.main' }} />,
      title: 'Real CTF Challenges',
      description: 'Practice web exploitation, cryptography, steganography, forensics, and binary exploitation with real-world scenarios.',
    },
    {
      icon: <EmojiObjectsIcon sx={{ fontSize: 60, color: 'primary.main' }} />,
      title: 'AI-Powered Hints',
      description: 'Get contextual hints generated by our ML model when you\'re stuck, without spoiling the solution.',
    },
    {
      icon: <TrendingUpIcon sx={{ fontSize: 60, color: 'primary.main' }} />,
      title: 'Dynamic Difficulty',
      description: 'Our ML engine adapts to your skill level, recommending challenges that match your current abilities.',
    },
    {
      icon: <GroupsIcon sx={{ fontSize: 60, color: 'primary.main' }} />,
      title: 'Competitive Learning',
      description: 'Climb the leaderboard, earn badges, and compete with hackers worldwide in a gamified learning environment.',
    },
  ];

  return (
    <Box>
      {/* Hero Section */}
      <Box
        sx={{
          background: 'linear-gradient(135deg, #0a0e27 0%, #1a2f4a 100%)',
          borderRadius: 4,
          p: 8,
          mb: 6,
          textAlign: 'center',
        }}
      >
        <Typography
          variant="h2"
          sx={{
            fontWeight: 700,
            mb: 2,
            background: 'linear-gradient(45deg, #00ff88 30%, #00ccff 90%)',
            WebkitBackgroundClip: 'text',
            WebkitTextFillColor: 'transparent',
          }}
        >
          Welcome to HacMan
        </Typography>
        <Typography variant="h5" sx={{ mb: 4, color: 'text.secondary' }}>
          ML-Powered Capture The Flag Platform
        </Typography>
        <Typography variant="body1" sx={{ mb: 4, maxWidth: 800, mx: 'auto' }}>
          Master cybersecurity skills through hands-on challenges with intelligent difficulty
          adjustment and AI-generated hints. Train safely, compete globally, and become an elite
          ethical hacker.
        </Typography>
        {!user ? (
          <Box sx={{ display: 'flex', gap: 2, justifyContent: 'center' }}>
            <Button
              component={Link}
              to="/register"
              variant="contained"
              size="large"
              sx={{
                px: 4,
                py: 1.5,
                fontSize: '1.1rem',
                background: 'linear-gradient(45deg, #00ff88 30%, #00ccff 90%)',
              }}
            >
              Get Started
            </Button>
            <Button
              component={Link}
              to="/login"
              variant="outlined"
              size="large"
              sx={{ px: 4, py: 1.5, fontSize: '1.1rem' }}
            >
              Login
            </Button>
          </Box>
        ) : (
          <Button
            component={Link}
            to="/challenges"
            variant="contained"
            size="large"
            sx={{
              px: 4,
              py: 1.5,
              fontSize: '1.1rem',
              background: 'linear-gradient(45deg, #00ff88 30%, #00ccff 90%)',
            }}
          >
            Start Hacking
          </Button>
        )}
      </Box>

      {/* Features Section */}
      <Container maxWidth="lg" sx={{ mb: 6 }}>
        <Typography variant="h4" sx={{ fontWeight: 700, mb: 4, textAlign: 'center' }}>
          Why Choose HacMan?
        </Typography>
        <Grid container spacing={4}>
          {features.map((feature, index) => (
            <Grid item xs={12} md={6} key={index}>
              <Card
                sx={{
                  height: '100%',
                  transition: 'transform 0.3s, box-shadow 0.3s',
                  '&:hover': {
                    transform: 'translateY(-8px)',
                    boxShadow: '0 12px 40px rgba(0, 255, 136, 0.3)',
                  },
                }}
              >
                <CardContent sx={{ textAlign: 'center', p: 4 }}>
                  <Box sx={{ mb: 2 }}>{feature.icon}</Box>
                  <Typography variant="h5" sx={{ fontWeight: 600, mb: 2 }}>
                    {feature.title}
                  </Typography>
                  <Typography variant="body1" color="text.secondary">
                    {feature.description}
                  </Typography>
                </CardContent>
              </Card>
            </Grid>
          ))}
        </Grid>
      </Container>

      {/* Stats Section */}
      <Box
        sx={{
          background: 'linear-gradient(135deg, #1a1f3a 0%, #2a2f4a 100%)',
          borderRadius: 4,
          p: 6,
          textAlign: 'center',
        }}
      >
        <Typography variant="h4" sx={{ fontWeight: 700, mb: 4 }}>
          Join the Community
        </Typography>
        <Grid container spacing={4}>
          <Grid item xs={12} md={4}>
            <Typography variant="h2" sx={{ color: 'primary.main', fontWeight: 700 }}>
              50+
            </Typography>
            <Typography variant="h6" color="text.secondary">
              CTF Challenges
            </Typography>
          </Grid>
          <Grid item xs={12} md={4}>
            <Typography variant="h2" sx={{ color: 'primary.main', fontWeight: 700 }}>
              5
            </Typography>
            <Typography variant="h6" color="text.secondary">
              Categories
            </Typography>
          </Grid>
          <Grid item xs={12} md={4}>
            <Typography variant="h2" sx={{ color: 'primary.main', fontWeight: 700 }}>
              ML
            </Typography>
            <Typography variant="h6" color="text.secondary">
              AI-Powered Learning
            </Typography>
          </Grid>
        </Grid>
      </Box>
    </Box>
  );
};

export default Home;